toolset: generate.generate:Generate
action: generate
arguments:
  tools:
  - toolset: practices.ddd.ddd:Ddd
    context:
      fidelity: tactics
      format: null
      path: null
      session: null
      workspace: null
