"""VSCode agent hook - deliver governed-asset manifest guidance once per chat, then reuse.

beforeReadFile / postToolUse / preToolUse:
  Scan the file's header for ``# @toolset-manifest`` lines, run each named
  toolset's manifest, and deliver the full guidance - that toolset's tools,
  actions, and every action's instructions (generate, document, validate,
  satisfy, ...) - into the Agent's context. The edit proceeds directly on
  the same touch that delivered the guidance; there is no separate "run
  compliance yourself first" step and nothing is ever denied.

  When the same conversation already received that governing toolset's
  guidance earlier in the chat (keyed by ``conversation_id`` + toolset
  command), later touches skip ``run_manifests`` and do not re-inject the
  blob — the agent keeps using guidance already in context (fidelity-tool
  format) without remanifesting.

This applies uniformly to every touch, by any caller (the main agent, an ad
hoc Task subagent, a launched ``@sub_agent`` tool), and recursively all the
way down to the base primitives - a context tool's own source file is itself
a governed asset generated by whichever tool built it, so editing
context_tools/bdd/bdd.py runs BDD's own manifest the same as editing any
asset BDD generated.

A manifest command that errors or times out is retried (see
``run_manifests``); a command still failing after every retry raises a loud,
all-caps ``user_message`` through the IDE's own notification channel rather
than being silently skipped. Mode (normal/verbose, see
``utilities.manifest_hook.manifest_gate_conf``) controls how much of this
shows up in ``user_message``.

See: primitives/tools/hooks/.context/manifest-gate-stories-sketch.md

History: this hook used to deny mutating edits until a separate, deliberate
``python -m tools run -`` invocation cleared the path (tracked in
hooks/.manifest_gate_clearance.json, cleared only via afterShellExecution).
That deny-until-cleared mechanism is retired - see the sketch's reconciliation
notes for why guidance-delivered-directly supersedes it end to end.
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[2]  # utilities/manifest_hook/ -> utilities/ -> abd-context-driven-delivery/
_LOG_FILE = Path(__file__).resolve().parent / "manifest_gate.log"
_DELIVERED_CACHE_PATH = Path(__file__).resolve().parent / ".manifest_gate_delivered.json"
_MANIFEST_PREFIXES = ("# @toolset-manifest", "# invoke-")
_SCAN_LINES = 15
_CATEGORY_DIRS = ("primitives", "utilities", "context_tools", "context_tools/actions")
_MAX_MANIFEST_RETRIES = 2
_NO_CONVERSATION = "_no_conversation"

if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))
for _cat in _CATEGORY_DIRS:
    _p = str(_REPO_ROOT / _cat)
    if _p not in sys.path:
        sys.path.insert(0, _p)

from utilities.manifest_hook import manifest_gate_conf  # noqa: E402
from utilities.manifest_hook.manifest_gate_conf import show_os_notification as _show_os_notification  # noqa: E402

_MUTATING_TOOLS = frozenset(
    {
        "Write",
        "StrReplace",
        "EditNotebook",
        "Delete",
        "delete_file",
        "search_replace",
        "write",
    }
)
_MANIFEST_CMD_RE = re.compile(r"^#\s*@toolset-manifest\s+(.+)$", re.IGNORECASE)


def _conversation_id(data: dict) -> str:
    cid = str(data.get("conversation_id") or "").strip()
    return cid or _NO_CONVERSATION


def _guidance_cache_keys(path: str, manifest_lines: list[str]) -> list[str]:
    """Stable keys for guidance already delivered this chat (prefer toolset)."""
    keys: list[str] = []
    for line in manifest_lines:
        if not line.startswith("# @toolset-manifest"):
            continue
        cmd = line.removeprefix("# @toolset-manifest").strip()
        if cmd:
            keys.append(f"cmd:{cmd}")
        toolset = toolset_from_manifest_lines([line])
        if toolset:
            keys.append(f"toolset:{toolset}")
    if not keys:
        try:
            keys.append(f"path:{Path(path).resolve()}")
        except OSError:
            keys.append(f"path:{path}")
    return keys


def _load_delivered_cache() -> dict[str, list[str]]:
    try:
        raw = json.loads(_DELIVERED_CACHE_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    if not isinstance(raw, dict):
        return {}
    out: dict[str, list[str]] = {}
    for cid, keys in raw.items():
        if isinstance(keys, list):
            out[str(cid)] = [str(k) for k in keys]
    return out


def _save_delivered_cache(cache: dict[str, list[str]]) -> None:
    try:
        _DELIVERED_CACHE_PATH.write_text(
            json.dumps(cache, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
    except OSError:
        pass


def guidance_already_delivered(conversation_id: str, keys: list[str]) -> bool:
    """True when every cache key was already marked delivered for this chat."""
    if not keys:
        return False
    delivered = set(_load_delivered_cache().get(conversation_id, []))
    return all(k in delivered for k in keys)


def mark_guidance_delivered(conversation_id: str, keys: list[str]) -> None:
    """Record that these guidance keys were delivered in this conversation."""
    if not keys:
        return
    cache = _load_delivered_cache()
    existing = set(cache.get(conversation_id, []))
    existing.update(keys)
    cache[conversation_id] = sorted(existing)
    _save_delivered_cache(cache)


def clear_delivered_cache() -> None:
    """Test helper — wipe the on-disk delivered-this-chat cache."""
    try:
        _DELIVERED_CACHE_PATH.unlink(missing_ok=True)
    except OSError:
        pass


def _pythonpath_env() -> dict[str, str]:
    """Env with repo + category dirs on PYTHONPATH for hybrid imports."""
    env = os.environ.copy()
    entries = [str(_REPO_ROOT)] + [str(_REPO_ROOT / name) for name in _CATEGORY_DIRS]
    existing = env.get("PYTHONPATH", "")
    prefix = os.pathsep.join(entries)
    env["PYTHONPATH"] = prefix if not existing else prefix + os.pathsep + existing
    env.setdefault("PYTHONIOENCODING", "utf-8")
    return env


def _log(mode: str, path: str, fired: bool, detail: str = "") -> None:
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    status = "FIRED" if fired else "skip"
    line = f"{ts} [{mode:4}] {status}  {path}"
    if detail:
        line += f"  - {detail}"
    try:
        with _LOG_FILE.open("a", encoding="utf-8") as fh:
            fh.write(line + "\n")
    except OSError:
        pass


def _find_python() -> str:
    """Prefer the repo venv Python; fall back to this interpreter."""
    for candidate in [
        _REPO_ROOT / ".venv" / "Scripts" / "python.exe",
        _REPO_ROOT / "venv" / "Scripts" / "python.exe",
        _REPO_ROOT / ".venv" / "bin" / "python",
        _REPO_ROOT / "venv" / "bin" / "python",
    ]:
        if candidate.is_file():
            return str(candidate)
    return sys.executable


def scan_manifest_lines(path: str) -> list[str]:
    """Return lines starting with manifest prefixes from the first _SCAN_LINES of path."""
    p = Path(path)
    if not p.is_file():
        return []
    lines: list[str] = []
    try:
        with p.open(encoding="utf-8", errors="ignore") as fh:
            for i, line in enumerate(fh):
                if i >= _SCAN_LINES:
                    break
                stripped = line.strip()
                if any(stripped.startswith(prefix) for prefix in _MANIFEST_PREFIXES):
                    lines.append(stripped)
    except OSError:
        return []
    return lines


def toolset_from_manifest_lines(manifest_lines: list[str]) -> str | None:
    for line in manifest_lines:
        match = _MANIFEST_CMD_RE.match(line)
        if not match:
            continue
        parts = match.group(1).split()
        if parts:
            return parts[-1]
    return None


def _run_manifest_command(parts: list[str]) -> str | None:
    """Run one manifest command once. Returns stdout, or None on error/timeout."""
    try:
        result = subprocess.run(
            parts,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            cwd=str(_REPO_ROOT),
            env=_pythonpath_env(),
            timeout=30,
        )
        return result.stdout
    except (subprocess.TimeoutExpired, OSError):
        return None


def run_manifests(manifest_lines: list[str]) -> tuple[str, list[str]]:
    """Run each @toolset-manifest command and return (combined output, failed commands).

    A correctly configured manifest should never fail. When one does, this
    retries it up to _MAX_MANIFEST_RETRIES times before giving up. A command
    still failing after every retry is reported in the second tuple element -
    never silently dropped - so the caller can raise a loud, exceptional
    failure notification (see _manifest_failure_notification) instead of
    quietly proceeding without that toolset's guidance.
    """
    python = _find_python()
    outputs: list[str] = []
    failures: list[str] = []
    for line in manifest_lines:
        if not line.startswith("# @toolset-manifest"):
            continue
        cmd_str = line.removeprefix("# @toolset-manifest").strip()
        parts = cmd_str.split()
        if parts and parts[0] == "python":
            parts[0] = python
        output = None
        for _attempt in range(1 + _MAX_MANIFEST_RETRIES):
            output = _run_manifest_command(parts)
            if output is not None:
                break
        if output is not None:
            if output.strip():
                outputs.append(output.strip())
        else:
            failures.append(cmd_str)
    return "\n\n".join(outputs), failures


def _manifest_failure_notification(path: str, failures: list[str]) -> str:
    """Super-obvious, all-caps failure notification - never a silent skip."""
    name = Path(path).name.upper()
    attempts = 1 + _MAX_MANIFEST_RETRIES
    commands = ", ".join(failures).upper()
    return (
        f"MANIFEST GATE FAILURE: COULD NOT LOAD THE MANIFEST FOR {name} "
        f"AFTER {attempts} ATTEMPTS ({commands}). A CORRECTLY CONFIGURED "
        "TOOLSET SHOULD NEVER FAIL HERE - CHECK ITS SETUP."
    )


def _verbose_trace_lines(path: str, manifest_lines: list[str]) -> list[str]:
    """Verbose-mode narration: hook fired -> manifest executing -> manifest loaded."""
    name = Path(path).name
    lines = [f"Manifest gate: hook fired for {name}"]
    for line in manifest_lines:
        if line.startswith("# @toolset-manifest"):
            cmd_str = line.removeprefix("# @toolset-manifest").strip()
            lines.append(f"Manifest gate: executing {cmd_str}")
    lines.append(f"Manifest gate: manifest loaded for {name}")
    return lines


def _build_user_message(
    path: str, manifest_lines: list[str], base_message: str, failures: list[str]
) -> str:
    """Overlay the base notification with a failure or verbose-mode narration."""
    if failures:
        return _manifest_failure_notification(path, failures)
    if manifest_gate_conf.read_mode() == "verbose":
        return "\n".join(_verbose_trace_lines(path, manifest_lines) + [base_message])
    return base_message


def _format_pre_message(path: str, manifest_lines: list[str], manifest_output: str) -> str:
    """Injected BEFORE a mutating edit — hard stop and mandatory workflow."""
    name = Path(path).name
    parts = [
        f"⛔ MANIFEST GATE — MANDATORY STOP BEFORE EDITING {name} ⛔",
        "",
        "This file is a governed asset. Its governing toolset's manifest has been",
        "loaded below. You MUST follow it before making any changes.",
        "",
        "REQUIRED STEPS — do not skip any:",
        "  1. Read the full manifest output below.",
        "  2. Follow response.instructions exactly — invoke the toolset's actions",
        "     (generate, satisfy, validate, scan, …) using `python -m tools run -`.",
        "  3. Do NOT write or edit code directly. Author changes only through the",
        "     toolset's own generate/satisfy actions.",
        "  4. After any change, run the toolset's scan and validate actions.",
        "",
        "Governing directives found in file header:",
        *[f"  {l}" for l in manifest_lines],
        "",
        "Manifest output — follow response.instructions from this:",
        manifest_output or "(none)",
    ]
    return "\n".join(parts)


def _format_post_message(path: str, manifest_lines: list[str], manifest_output: str) -> str:
    """Injected AFTER a mutating edit — mandatory satisfy/validate directive."""
    name = Path(path).name
    parts = [
        f"⚠️ MANIFEST GATE — EDIT LANDED ON GOVERNED ASSET {name} ⚠️",
        "",
        "A direct edit was just made to a governed asset. You MUST now run satisfy",
        "and validate through the governing toolset before this task is complete.",
        "",
        "MANDATORY NEXT STEPS — do not skip:",
        "  1. Run the toolset's `satisfy` action to bring the asset into compliance.",
        "     This includes generating any missing specs, tests, or context files.",
        "  2. Run `validate` and fix every reported violation.",
        "  3. Run `scan` to confirm no remaining issues.",
        "  All three steps are required. The task is NOT done until validate passes.",
        "",
        "Governing directives found in file header:",
        *[f"  {l}" for l in manifest_lines],
        "",
        "Manifest output (toolset instructions):",
        manifest_output or "(none)",
    ]
    return "\n".join(parts)


def _user_notification(path: str) -> str:
    return f"Manifest gate: ran header for {Path(path).name}"


def _extract_path(data: dict) -> str:
    """Extract file path from hook payload."""
    ti = data.get("tool_input") or {}
    return (
        ti.get("path")
        or ti.get("file_path")
        or data.get("file_path")
        or ""
    )


def _tool_name(data: dict) -> str:
    return str(data.get("tool_name") or data.get("tool") or "")


def _is_mutating_tool(data: dict) -> bool:
    name = _tool_name(data)
    if name in _MUTATING_TOOLS:
        return True
    ti = data.get("tool_input") or {}
    if ti.get("contents") is not None or ti.get("content") is not None:
        return True
    if ti.get("old_string") is not None or ti.get("new_string") is not None:
        return True
    return False


def _deliver_guidance(mode: str, path: str, lines: list[str], *, post: bool = False) -> dict:
    """Run every named governing toolset's manifest for ``path`` and build the
    hook response that delivers the guidance.

    post=True selects the post-edit satisfy/validate directive; False (default)
    selects the pre-edit hard-stop directive.
    """
    manifest_output, failures = run_manifests(lines)
    if not manifest_output and not failures:
        _log(mode, path, fired=False, detail="header ran but produced no output")
        return {}
    _log(mode, path, fired=True, detail=f"{len(lines)} line(s)")
    name = Path(path).name
    if failures:
        _show_os_notification(
            "MANIFEST GATE FAILURE",
            _manifest_failure_notification(path, failures),
            error=True,
        )
    else:
        _show_os_notification(
            "Manifest Gate",
            f"{'Satisfy required' if post else 'Stop — follow manifest'} for {name}",
        )
    fmt = _format_post_message if post else _format_pre_message
    return {
        "agent_message": fmt(path, lines, manifest_output),
        "user_message": _build_user_message(path, lines, _user_notification(path), failures),
    }


def handle_before_read_file(data: dict) -> dict:
    """beforeReadFile - deliver guidance; nothing to allow/deny on a read."""
    path = _extract_path(data)
    if not path:
        return {}
    lines = scan_manifest_lines(path)
    if not lines:
        _log("read", path, fired=False)
        return {}
    return _deliver_guidance("read", path, lines)


def handle_post_tool_use(data: dict) -> dict:
    """postToolUse - deliver guidance as additional_context after any touch."""
    path = _extract_path(data)
    if not path:
        return {}
    lines = scan_manifest_lines(path)
    if not lines:
        _log("post", path, fired=False)
        return {}
    delivered = _deliver_guidance("post", path, lines, post=True)
    if not delivered:
        return {}
    delivered["additional_context"] = delivered.pop("agent_message")
    return delivered


def handle_pre_tool_use(data: dict) -> dict:
    """preToolUse - deliver guidance; never denies. The edit proceeds directly
    on the same touch that delivered it - see the sketch's "Deliver Guidance
    Once Per Chat, Then Reuse It" story for the full rationale. Applies
    uniformly regardless of caller (main agent, ad hoc Task subagent, or a
    launched @sub_agent tool).
    """
    path = _extract_path(data)
    if not path or not _is_mutating_tool(data) or not Path(path).is_file():
        return {"permission": "allow"}
    lines = scan_manifest_lines(path)
    if not lines:
        _log("pre ", path, fired=False)
        return {"permission": "allow"}
    delivered = _deliver_guidance("pre ", path, lines)
    delivered["permission"] = "allow"
    return delivered


def parse_hook_payload(raw: bytes) -> dict:
    """Parse the JSON payload sent by Cursor on stdin.

    Cursor prepends two consecutive UTF-8 BOM markers (\\xef\\xbb\\xbf twice).
    Python's utf-8-sig codec only strips one, leaving a second BOM that breaks
    json.loads. We strip all leading BOM bytes before decoding.
    """
    stripped = raw.lstrip(b"\xef\xbb\xbf")
    return json.loads(stripped.decode("utf-8"))


def main() -> None:
    mode = sys.argv[1] if len(sys.argv) > 1 else "post"
    raw = sys.stdin.buffer.read()
    data = parse_hook_payload(raw)
    if mode == "read":
        result = handle_before_read_file(data)
    elif mode == "pre":
        result = handle_pre_tool_use(data)
    else:
        result = handle_post_tool_use(data)
    json.dump(result, sys.stdout)


if __name__ == "__main__":
    main()
