toolset: satisfy.satisfy:Satisfy
action: satisfy
arguments:
  tools:
  - toolset: practices.stories.stories:Stories
    context:
      fidelity: <fidelity>
      format: null
      path: null
      session: null
      workspace: null
