toolset: validate.validate:Validate
action: validate
arguments:
  tools:
  - toolset: practices.stories.stories:Stories
    context:
      fidelity: <fidelity>
      format: null
      path: null
      session: null
      workspace: null
