toolset: generate.generate:Generate
action: generate
arguments:
  tools:
  - toolset: context_tools.bdd.bdd:Bdd
    context:
      fidelity: behavior
      format: null
      path: null
      session: null
      workspace: null
