# @toolset-manifest python -m tools manifest context_tools.bdd.bdd:Bdd
# Agent reading this file: run line 1 manifest, then python -m tools run -. Follow response.instructions only.
# Do not author behavior from this Python source.
"""Fixture toolset generated by BDD - drives hooks_agent_spec.py scenarios end-to-end.

``GatedWidget`` is a minimal toolset that demonstrates manifest gating on a BDD-generated asset:
editing this file triggers the BDD manifest, not GatedWidget's own manifest.
``_REVISION`` is a throwaway marker some scenarios edit directly to prove a write landed on disk.
"""
from __future__ import annotations

from primitives.actions.action import agent_instructions, agentic_toolset
from sub_agent.sub_agent import sub_agent
from tools.tool import resource, agent_tool

_REVISION = 1


@agentic_toolset
class GatedWidget:
    """Minimal manifest-gated fixture for hooks_agent_spec.py scenarios."""

    def __init__(self) -> None:
        self._label = "widget"
        self._names: list[str] = []

    @property
    @resource
    def label(self) -> str:
        """Current label."""
        return self._label

    @agent_tool
    def rename(self, label: str) -> str:
        """Rename the widget - plain tool, no gate semantics of its own."""
        self._label = label
        return f"renamed to {label}"

    @agent_instructions
    def satisfy(self) -> str:
        """Acknowledge manifest compliance for this fixture - no real generation work.
        Exists so the invoke-edit directive above has a real action to execute."""
        return (
            "GatedWidget compliance acknowledged - edits to gated_widget.py are "
            "cleared for this session."
        )

    @agent_tool
    def hello_world(self, name: str) -> str:
        """Ask for the caller's name and introduce the widget.

        Each distinct name is remembered so ``whos_all_here`` and ``goodbye``
        can report or farewell everyone who was greeted.
        """
        if name not in self._names:
            self._names.append(name)
        return (
            f"Hello, {name}! I'm Gated Widget, part of the Agile by Design team. "
            "It's nice to meet you."
        )

    @agent_tool
    def whos_all_here(self) -> str:
        """Return everyone introduced through ``hello_world`` to the chat."""
        if not self._names:
            return "No one has said hello yet."
        return f"Everyone who's here: {', '.join(self._names)}."

    @agent_tool
    def goodbye(self, farewell: str) -> str:
        """Accept a farewell from the caller and say goodbye to everyone.

        The caller supplies any parting message they like (e.g. ``"See you soon"``).
        The tool echoes it back as a warm send-off that names everyone introduced
        through ``hello_world``.
        """
        if self._names:
            named = ", ".join(self._names)
            named_goodbye = f"Goodbye, {named}, and "
        else:
            named_goodbye = ""
        return (
            f"{farewell}! {named_goodbye}goodbye to everyone — "
            "it was great having you all here."
        )

    @sub_agent
    @agent_tool
    def launch_revision_bump(self) -> str:
        """Launch a non-blocking background sub-agent. That sub-agent must open
        primitives/tools/hooks/examples/gated_widget/gated_widget.py directly (a plain
        file edit, not a `tools run` call) and change the module-level `_REVISION = 1`
        line to `_REVISION = 2`, then report back the exact tool result it received for
        that edit - in particular any `permission`, `agent_message`, or `user_message`
        fields that came back with it."""
