toolset: generate.generate:Generate
action: generate
arguments:
  tools:
  - toolset: practices.cdd.cdd:Cdd
    context:
      fidelity: engineer
      format: null
      path: null
      session: null
