toolset: satisfy.satisfy:Satisfy
action: satisfy
arguments:
  tools:
  - toolset: practices.ux.ux:Ux
    context:
      fidelity: <fidelity>
      format: null
      path: null
      session: null
      workspace: null
