"""Knowledge graph model — one practice graph across Stories, CE, DDD, and BDD."""

from practices.bdd.model import Context, Description, Observation
from practices.clean_engineering.model.operation import Operation, Parameter
from practices.clean_engineering.model.property import Property
from practices.ddd.model import (
    Aggregate,
    BoundedContext,
    DomainEvent,
    DomainService,
    Entity,
    EntityRoot,
    Repository,
    ValueObject,
)

from .graph_node import GraphNodeMixin, GraphRelationship, Kind
from .nodes import (
    GraphAggregate,
    GraphBackground,
    GraphBoundedContext,
    GraphClass,
    GraphDescription,
    GraphDomainEvent,
    GraphDomainService,
    GraphEntity,
    GraphEntityRoot,
    GraphEpic,
    GraphExample,
    GraphModule,
    GraphObservation,
    GraphOperation,
    GraphParameter,
    GraphProperty,
    GraphRepository,
    GraphScenario,
    GraphStep,
    GraphStory,
    GraphSubEpic,
    GraphValueObject,
)
from .practice_graph import PracticeGraph

__all__ = [
    "Aggregate",
    "BoundedContext",
    "Context",
    "Description",
    "DomainEvent",
    "DomainService",
    "Entity",
    "EntityRoot",
    "GraphAggregate",
    "GraphBackground",
    "GraphBoundedContext",
    "GraphClass",
    "GraphDomainEvent",
    "GraphDomainService",
    "GraphEntity",
    "GraphEntityRoot",
    "GraphDescription",
    "GraphEpic",
    "GraphExample",
    "GraphModule",
    "GraphNodeMixin",
    "GraphObservation",
    "GraphOperation",
    "GraphParameter",
    "GraphProperty",
    "GraphRepository",
    "GraphRelationship",
    "GraphValueObject",
    "GraphScenario",
    "GraphStep",
    "GraphStory",
    "GraphSubEpic",
    "Kind",
    "Observation",
    "Operation",
    "Parameter",
    "PracticeGraph",
    "Property",
    "Repository",
    "ValueObject",
]
