toolset: generate.generate:Generate
action: generate
arguments:
  tools:
  - toolset: context_tools.ux.ux:Ux
    context:
      fidelity: front_end_code
      format: null
      path: null
      session: null
      workspace: null
